version: "3"

services:
  api:
    image: mattjvincent/qtlapi:${DOCKER_QTLAPI_VERSION}
    env_file:
      - '.env'
    ports:
     - ${PORT_API}:8001
    volumes:
     - ${FILE_RDATA}:/app/qtlapi/data/api.RData
     - ${FILE_SNPDB}:/app/qtlapi/data/ccfounders.sqlite

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    ports:
      - ${PORT_REDIS}:6379
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    image: mattjvincent/qtlweb:${DOCKER_QTLWEB_VERSION}
    env_file:
      - '.env'
    ports:
      - ${PORT_GUNICORN}:${PORT_GUNICORN}
    volumes:
      - ${FILE_QTLVIEWER_SETTINGS}:${QTLVIEWER_SETTINGS}
      - ${DIR_QTLVIEWER_CACHE}:${QTLVIEWER_CACHE}
    command: >
      gunicorn -w ${GUNICORN_WORKERS} -b 0.0.0.0:${PORT_GUNICORN} "qtlweb.app:create_app()"

  celery:
    image: mattjvincent/qtlweb:${DOCKER_QTLWEB_VERSION}
    command: celery worker -l info -A qtlweb.modules.api.tasks
    env_file:
      - '.env'
    volumes:
      - ${FILE_QTLVIEWER_SETTINGS}:${QTLVIEWER_SETTINGS}
      - ${DIR_QTLVIEWER_CACHE}:${QTLVIEWER_CACHE}

  flower:
    image: mattjvincent/qtlweb:${DOCKER_QTLWEB_VERSION}
    command: flower -A qtlweb.modules.api.tasks --port=5555
    env_file:
      - '.env'
    ports:
      - '${PORT_FLOWER}:5555'
    volumes:
      - ${FILE_QTLVIEWER_SETTINGS}:${QTLVIEWER_SETTINGS}
      - ${DIR_QTLVIEWER_CACHE}:${QTLVIEWER_CACHE}

volumes:
  redis:


