version: '3'

services:

  website:
    build: .
    # environment variables will be passed through to container
    env_file:
      '.env'
    command: gunicorn -c "python:config.gunicorn" --reload "qtlweb.app:create_app()"
    volumes:
      - ${FILE_QTLVIEWER_SETTINGS}:${QTLVIEWER_SETTINGS}
      - ${DIR_QTLVIEWER_CACHE}:${QTLVIEWER_CACHE}
    ports:
      - ${PORT_GUNICORN}:${PORT_GUNICORN}

  redis:
    image: 'redis:4.0.11-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  celery:
    build: .
    # environment variables will be passed through to container
    env_file:
      '.env'
    command: celery worker -l info -A qtlweb.modules.api.tasks -E
    volumes:
      - ${FILE_QTLVIEWER_SETTINGS}:${QTLVIEWER_SETTINGS}
      - ${DIR_QTLVIEWER_CACHE}:${QTLVIEWER_CACHE}

volumes:
  redis:

# docker network create --attachable qtlviewer
networks:
  default:
    external:
      name: qtlviewer


